# $OpenBSD: Makefile,v 1.7 2018/05/31 21:04:09 sthen Exp $

V=		5.7.28
SNAPPY_V=	1.1.4
REVISION=	0

# for beta/rc testing; from URLs in UniFi-Beta-Blog if you have access
BUILD_V=	-5c442c6b54

.include <bsd.port.mk>
